trigger:
- main

jobs:
- job: cypress_test
  displayName: 'Run on Chrome 83'
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: 'cypress/browsers:node12.18.0-chrome83-ff77'
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '12.18.0'
    displayName: 'Install Node.js 12.18.0'

  - script: |
      npm ci
      $(npm bin)/cypress verify
    displayName: 'Install cypress and verify'

  - script: npm run test
    displayName: 'Run Cypress tests'
    continueOnError: false
