name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Trigger API Testing
    runs-on: ubuntu-latest
    steps:
      - name: API Testing
        run: |
          echo "Start the Cypress Test"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: adminvns
          repo: cypress_reports
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          workflow_file_name: cypress-report.yml
      - name: API Testing..
        run: |
          echo "Success!!"
          sleep 10s
